logging:
  level:
    org.springframework.security: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://oauth-service:5000/uaa/users/current